# Generated by Django 3.2.3 on 2021-07-15 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tiempo', models.CharField(max_length=2)),
                ('riesgo', models.DecimalField(decimal_places=0, max_digits=1)),
                ('dinero', models.DecimalField(decimal_places=0, max_digits=12)),
                ('metrica', models.CharField(max_length=25)),
                ('archivo', models.CharField(max_length=105)),
            ],
            options={
                'db_table': 'portafolios',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='UsuarioPortafolio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('objetivo', models.CharField(max_length=100)),
                ('dinero', models.DecimalField(decimal_places=0, max_digits=12)),
                ('tiempo', models.CharField(max_length=2)),
                ('riesgo', models.DecimalField(decimal_places=0, max_digits=1)),
                ('fecha_visita', models.DateField()),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.portafolio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.usuario')),
            ],
            options={
                'db_table': 'usuarios_portafolios',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('asunto', models.CharField(max_length=100)),
                ('mensaje', models.CharField(max_length=2000)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.usuario')),
            ],
            options={
                'db_table': 'comentarios',
            },
        ),
    ]
