# Generated by Django 3.2.3 on 2021-07-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioportafolio',
            name='metrica',
            field=models.CharField(default='beta_std_dev', max_length=25),
            preserve_default=False,
        ),
    ]
